  %i = alloca i32
  %n = alloca i32
  %r0 = add i32 10, 0
  store i32 %r0, i32* %i
  %r1 = add i32 0, 0
  store i32 %r1, i32* %n
L0:
  %r2 = load i32, i32* %i
  %r3 = add i32 0, 0
  %r4 = icmp sgt i32 %r2, %r3
  br i1 %r4, label %L1, label %L2
L1:
  %r5 = load i32, i32* %n
  %r6 = add i32 1, 0
  %r7 = add i32 %r5, %r6
  store i32 %r7, i32* %n
  %r8 = load i32, i32* %i
  %r9 = add i32 1, 0
  %r10 = sub i32 %r8, %r9
  store i32 %r10, i32* %i
  br label %L0
L2:
