define i32 @f() {
L0:
  %a = alloca i32
  %b = alloca i32
  %r0 = add i32 2, 0
  store i32 %r0, i32* %a
  %r1 = load i32, i32* %a
  %r2 = add i32 3, 0
  %r3 = icmp sgt i32 %r1, %r2
  br i1 %r3, label %L1, label %L2
L1:
  %r4 = add i32 2, 0
  store i32 %r4, i32* %b
  br label L3
L2:
  %r5 = add i32 6, 0
  store i32 %r5, i32* %b
  br label L3
L3:
  %r6 = load i32, i32* %b
  ret i32 %r6
}
define i32 @main() {
L0:
  %a = alloca i32
  %b = alloca i32
  %r0 = add i32 2, 0
  store i32 %r0, i32* %a
  %r1 = load i32, i32* %a
  %r2 = add i32 3, 0
  %r3 = icmp sgt i32 %r1, %r2
  br i1 %r3, label %L1, label %L2
L1:
  %r4 = add i32 2, 0
  store i32 %r4, i32* %b
  br label L3
L2:
  %r5 = add i32 6, 0
  store i32 %r5, i32* %b
  br label L3
L3:
  %r6 = load i32, i32* %b
  ret i32 %r6
}
