define i32 @g(float %a, i32 %b) {
L0:
  %a.addr = alloca float
  store float %a, float* %a.addr
  %b.addr = alloca i32
  store i32 %b, i32* %b.addr
  %r = alloca i32
  %r0 = load float, float* %a.addr
  %r1 = fptosi float %r0 to i32
  store i32 %r1, i32* %r
  %r2 = load float, float* %a.addr
  %r3 = load i32, i32* %b.addr
  %r4 = sitofp i32 %r3 to float
  %r5 = fadd float %r2, %r4
  store float %r5, float* %a
  %r6 = load i32, i32* %r
  %r7 = load float, float* %a.addr
  %r8 = sitofp i32 %r6 to float
  %r9 = fadd float %r8, %r7
  %r10 = fptosi float %r9 to i32
  store i32 %r10, i32* %r
  %r11 = load i32, i32* %r
  ret i32 %r11
}
define void @f() {
L0:
  %a = alloca float
  %b = alloca i32
  %c = alloca i32
  %r0 = fadd float 0x3ff8000000000000, 0x0000000000000000
  store float %r0, float* %a
  %r1 = add i32 2, 0
  store i32 %r1, i32* %b
  %r2 = load float, float* %a
  %r3 = load i32, i32* %b
  %r4 = call i32 @g(float %r2, i32 %r3)
  store i32 %r4, i32* %c
}
