define i32 @main() {
L0:
  %a = alloca i32
  %b = alloca i32
  %r0 = add i32 0, 0
  store i32 %r0, i32* %a
  %r1 = load i32, i32* %a
  %r2 = add i32 0, 0
  %r3 = icmp eq i32 %r1, %r2
  br i1 %r3, label %L1, label %L3
L3:
  %r4 = load i32, i32* %a
  %r5 = add i32 1, 0
  %r6 = icmp eq i32 %r4, %r5
  br i1 %r3, label %L1, label %L4
L4:
  %r7 = load i32, i32* %a
  %r8 = add i32 2, 0
  %r9 = icmp eq i32 %r7, %r8
  br i1 %r3, label %L1, label %L2
L1:
  %r10 = add i32 1, 0
  store i32 %r10, i32* %a
  br label L2
L2:
  %r11 = load i32, i32* %a
  %r12 = add i32 1, 0
  %r13 = icmp eq i32 %r11, %r12
  br i1 %r13, label %L5, label %L7
L7:
  %r14 = load i32, i32* %a
  %r15 = add i32 2, 0
  %r16 = icmp eq i32 %r14, %r15
  br i1 %r13, label %L5, label %L8
L8:
  %r17 = load i32, i32* %a
  %r18 = add i32 3, 0
  %r19 = icmp eq i32 %r17, %r18
  br i1 %r13, label %L5, label %L6
L5:
  %r20 = add i32 2, 0
  store i32 %r20, i32* %a
  br label L9
L6:
  %r21 = add i32 3, 0
  store i32 %r21, i32* %a
  br label L9
L9:
  %r22 = load i32, i32* %a
  ret i32 %r22
}
